"use strict";

// Art-first landing flow: the visitor gets three finished art cards free
// (boot + two presses), then cards arrive verse-only and the one free
// generation is offered. Generation, free-image metering, and analytics all
// ride the same rails as index.html — /api/picture with X-Enlighten-Device,
// the shared enlighten.freeImage.v1 localStorage key, gtag + /api/marketing-event.

// Curated deck: each background was generated by scripts/generate-art-first-deck.js
// through the production pipeline in api/picture.js, so the free-taste art is
// stylistically identical to what live generation produces for these verses.
const DECK = [
  {
    bg: "assets/art-first/bg-1.jpg",
    reference: "Psalm 23:1–2",
    text: "The Lord is my shepherd; I shall not want. He maketh me to lie down in green pastures: he leadeth me beside the still waters.",
  },
  {
    bg: "assets/art-first/bg-2.jpg",
    reference: "Isaiah 41:10",
    text: "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.",
  },
  {
    bg: "assets/art-first/bg-3.jpg",
    reference: "Philippians 4:7",
    text: "And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.",
  },
  {
    bg: "assets/art-first/bg-4.jpg",
    reference: "John 8:12",
    text: "Then spake Jesus again unto them, saying, I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life.",
  },
  {
    bg: "assets/art-first/bg-5.jpg",
    reference: "Psalm 46:10",
    text: "Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth.",
  },
  {
    bg: "assets/art-first/bg-6.jpg",
    reference: "Matthew 11:28",
    text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest.",
  },
  {
    bg: "assets/art-first/bg-7.jpg",
    reference: "Jeremiah 29:11",
    text: "For I know the thoughts that I think toward you, saith the Lord, thoughts of peace, and not of evil, to give you an expected end.",
  },
  {
    bg: "assets/art-first/bg-8.jpg",
    reference: "1 Corinthians 16:14",
    text: "Let all your things be done with charity.",
  },
];

const CREATE_PROMPT_AFTER_PRESSES = 3;

// Shared with script.js so metering and identity are one story across pages:
// a visitor who spends the free image here is walled on index.html too.
const FREE_IMAGE_STORAGE_KEY = "enlighten.freeImage.v1";
// Flow state survives same-tab round trips (settings gear, subscribe deep
// link → Back) so returning lands on the card the visitor left, not a reset
// deck handing out three more free art cards. Session-scoped on purpose: a
// fresh visit starts the experience over.
const SESSION_STORAGE_KEY = "enlighten.artFirst.session.v1";
const DEVICE_ID_STORAGE_KEY = "enlighten.deviceId.v1";
const IMAGE_PRODUCT_ID = "enlighten_ai_images_monthly";
const PRODUCTION_ORIGIN = "https://www.enlighten-me.co";

const cardA = document.getElementById("cardA");
const cardB = document.getElementById("cardB");
const pressMeButton = document.getElementById("pressMeButton");
const copyButton = document.getElementById("copyButton");
const saveButton = document.getElementById("saveButton");
const shareButton = document.getElementById("shareButton");
const createPrompt = document.getElementById("createPrompt");
const createButton = document.getElementById("createButton");
const dismissPrompt = document.getElementById("dismissPrompt");
const createModal = document.getElementById("createModal");
const createProgress = document.getElementById("createProgress");
const createDone = document.getElementById("createDone");
const createError = document.getElementById("createError");
const createErrorBody = document.getElementById("createErrorBody");
const createErrorClose = document.getElementById("createErrorClose");
const closeModal = document.getElementById("closeModal");
const paywallModal = document.getElementById("paywallModal");
const paywallSignup = document.getElementById("paywallSignup");
const paywallClose = document.getElementById("paywallClose");

let deckOrder = [];
let deckPosition = 0;
let pressCount = 0;
let frontIsA = true;
let showingTextOnly = false;
let freeArtUsed = false;
let pressesSinceFreeArt = 0;
let isGenerating = false;

function saveSession() {
  try {
    if (typeof sessionStorage === "undefined" || !deckOrder.length) return;
    const state = { deckOrder, deckPosition, pressCount, freeArtUsed, pressesSinceFreeArt, showingTextOnly };
    const generated = DECK.find((card) => card.generatedSrc);
    try {
      sessionStorage.setItem(SESSION_STORAGE_KEY, JSON.stringify({ ...state, generatedRef: generated?.reference, generatedSrc: generated?.generatedSrc }));
    } catch (error) {
      // The generated image data URL can blow the storage quota — keep the
      // flow position even if the artwork itself can't ride along.
      sessionStorage.setItem(SESSION_STORAGE_KEY, JSON.stringify(state));
    }
  } catch (error) {
    // private mode / quota — worst case the flow restarts, as before
  }
}

// Returns { textOnly } when a saved session was restored, false otherwise.
// Must run before prerenderDeck so a restored generatedSrc is what renders.
function restoreSession() {
  try {
    if (typeof sessionStorage === "undefined") return false;
    const raw = sessionStorage.getItem(SESSION_STORAGE_KEY);
    if (!raw) return false;
    const saved = JSON.parse(raw);
    if (!Array.isArray(saved.deckOrder) || saved.deckOrder.length !== DECK.length) return false;
    deckOrder = saved.deckOrder;
    deckPosition = Math.min(Math.max(saved.deckPosition || 0, 0), DECK.length - 1);
    pressCount = saved.pressCount || 0;
    freeArtUsed = Boolean(saved.freeArtUsed);
    pressesSinceFreeArt = saved.pressesSinceFreeArt || 0;
    if (saved.generatedRef && saved.generatedSrc) {
      const card = DECK.find((entry) => entry.reference === saved.generatedRef);
      if (card) card.generatedSrc = saved.generatedSrc;
    }
    // If the visitor left while looking at their generated card but the image
    // didn't fit in storage, fall back to verse-only rather than showing
    // curated art they no longer have free access to.
    let textOnly = Boolean(saved.showingTextOnly);
    if (!textOnly && freeArtUsed && !currentCard().generatedSrc) textOnly = true;
    return { textOnly };
  } catch (error) {
    return false;
  }
}

function isLocalStaticOrigin() {
  return ["localhost", "127.0.0.1"].includes(window.location.hostname);
}

function apiUrl(path) {
  return isLocalStaticOrigin() ? `${PRODUCTION_ORIGIN}${path}` : path;
}

function getDeviceId() {
  try {
    if (typeof localStorage === "undefined") return "";
    let id = localStorage.getItem(DEVICE_ID_STORAGE_KEY);
    if (!id) {
      id = window.crypto?.randomUUID?.() || `dev-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
      localStorage.setItem(DEVICE_ID_STORAGE_KEY, id);
    }
    return id;
  } catch (error) {
    return "";
  }
}

function isFreeImageAvailable() {
  try {
    if (typeof localStorage === "undefined") return true;
    return localStorage.getItem(FREE_IMAGE_STORAGE_KEY) !== "used";
  } catch (error) {
    return true;
  }
}

function markFreeImageUsed() {
  try {
    if (typeof localStorage !== "undefined") {
      localStorage.setItem(FREE_IMAGE_STORAGE_KEY, "used");
    }
  } catch (error) {
    // private mode / quota — the server still enforces the one-image limit
  }
}

// Mirrors trackMarketingEvent in script.js: GA4 via gtag plus a beacon to
// /api/marketing-event for Vercel Analytics. Localhost stays silent so dev
// runs don't pollute the funnels.
function track(eventName, data = {}) {
  if (isLocalStaticOrigin()) {
    console.info("[art-first-analytics]", eventName, data);
    return;
  }

  try {
    if (typeof window.gtag === "function" && window.GA4_MEASUREMENT_ID) {
      window.gtag("event", eventName, { send_to: window.GA4_MEASUREMENT_ID, page: "art-first", ...data });
    }
  } catch (error) {
    // analytics must never break the page
  }

  try {
    const body = JSON.stringify({ event: eventName, data: { page: "art-first", ...data } });
    const url = apiUrl("/api/marketing-event");
    if (navigator.sendBeacon) {
      navigator.sendBeacon(url, new Blob([body], { type: "application/json" }));
    } else {
      fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body, keepalive: true }).catch(() => {});
    }
  } catch (error) {
    // ditto
  }
}

function shuffle(array) {
  const copy = array.slice();
  for (let i = copy.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}

// ---------------------------------------------------------------------------
// Card renderer — lifted verbatim from script.js (wrapCanvasText,
// drawRoundedRect, drawShareCardText, renderShareCardCanvas) so this card is
// the production share card. Only difference: passage/image come from the
// curated deck instead of app state, and the translation tag is fixed to KJV.
// ---------------------------------------------------------------------------

function wrapCanvasText(context, text, maxWidth) {
  const words = text.split(/\s+/).filter(Boolean);
  const lines = [];
  let line = "";

  for (const word of words) {
    const testLine = line ? `${line} ${word}` : word;
    if (context.measureText(testLine).width > maxWidth && line) {
      lines.push(line);
      line = word;
    } else {
      line = testLine;
    }
  }

  if (line) lines.push(line);
  return lines;
}

function drawRoundedRect(context, x, y, width, height, radius) {
  context.beginPath();
  context.moveTo(x + radius, y);
  context.lineTo(x + width - radius, y);
  context.quadraticCurveTo(x + width, y, x + width, y + radius);
  context.lineTo(x + width, y + height - radius);
  context.quadraticCurveTo(x + width, y + height, x + width - radius, y + height);
  context.lineTo(x + radius, y + height);
  context.quadraticCurveTo(x, y + height, x, y + height - radius);
  context.lineTo(x, y + radius);
  context.quadraticCurveTo(x, y, x + radius, y);
  context.closePath();
}

function drawShareCardText(context, text, reference, compact = false) {
  const maxWidth = compact ? 920 : 940;
  const minFont = compact ? 30 : 42;
  const maxLines = compact ? 6 : 10;
  const centerY = compact ? 1060 : 720;
  const minTop = compact ? 830 : 200;
  const referenceGap = compact ? 44 : 60;
  const referenceFontSize = compact ? 32 : 42;
  let quoteFontSize = compact
    ? (text.length > 330 ? 38 : text.length > 220 ? 46 : 54)
    : (text.length > 330 ? 56 : text.length > 220 ? 66 : 76);
  let lines = [];

  do {
    context.font = `${quoteFontSize}px Georgia, serif`;
    lines = wrapCanvasText(context, `“${text}”`, maxWidth);
    if (lines.length <= maxLines || quoteFontSize <= minFont) break;
    quoteFontSize -= 4;
  } while (quoteFontSize >= minFont);

  const lineHeight = quoteFontSize * 1.34;
  const quoteBlockHeight = lines.length * lineHeight;
  let y = Math.max(minTop, centerY - quoteBlockHeight / 2);

  context.fillStyle = "#f8fafc";
  context.textAlign = "center";
  context.textBaseline = "alphabetic";
  context.font = `${quoteFontSize}px Georgia, serif`;

  for (const line of lines) {
    context.fillText(line, 540, y, maxWidth);
    y += lineHeight;
  }

  context.fillStyle = "#facc15";
  context.font = `700 ${referenceFontSize}px -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif`;
  context.fillText(`— ${reference} (KJV)`, 540, y + referenceGap, maxWidth);
}

function loadImage(src) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error(`Could not load ${src}`));
    img.src = src;
  });
}

async function renderCard(card, withArt = true) {
  const canvas = document.createElement("canvas");
  canvas.width = 1080;
  canvas.height = 1350;
  const context = canvas.getContext("2d");
  const width = canvas.width;
  const height = canvas.height;

  const imageForCanvas = withArt ? await loadImage(card.generatedSrc || card.bg) : null;

  const background = context.createLinearGradient(0, 0, width, height);
  background.addColorStop(0, "#0b1020");
  background.addColorStop(0.48, "#172554");
  background.addColorStop(1, "#111827");
  context.fillStyle = background;
  context.fillRect(0, 0, width, height);

  const glowOne = context.createRadialGradient(170, 150, 0, 170, 150, 620);
  glowOne.addColorStop(0, "rgba(250, 204, 21, 0.34)");
  glowOne.addColorStop(1, "rgba(250, 204, 21, 0)");
  context.fillStyle = glowOne;
  context.fillRect(0, 0, width, height);

  const glowTwo = context.createRadialGradient(900, 1120, 0, 900, 1120, 620);
  glowTwo.addColorStop(0, "rgba(59, 130, 246, 0.34)");
  glowTwo.addColorStop(1, "rgba(59, 130, 246, 0)");
  context.fillStyle = glowTwo;
  context.fillRect(0, 0, width, height);

  context.textAlign = "center";
  context.fillStyle = "#facc15";
  context.font = "800 24px -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif";
  context.letterSpacing = "4px";
  context.fillText("ENLIGHTEN-ME", 540, 80);
  context.letterSpacing = "0px";

  if (withArt) {
    context.save();
    drawRoundedRect(context, 24, 120, 1032, 650, 36);
    context.clip();
    const sourceRatio = imageForCanvas.naturalWidth / imageForCanvas.naturalHeight;
    const targetRatio = 1032 / 650;
    let drawW, drawH, drawX, drawY;
    if (sourceRatio > targetRatio) {
      drawH = 650;
      drawW = drawH * sourceRatio;
      drawX = 24 + (1032 - drawW) / 2;
      drawY = 120;
    } else {
      drawW = 1032;
      drawH = drawW / sourceRatio;
      drawX = 24;
      drawY = 120 + (650 - drawH) / 2;
    }
    context.drawImage(imageForCanvas, drawX, drawY, drawW, drawH);
    context.restore();

    context.save();
    context.fillStyle = "rgba(15, 23, 42, 0.78)";
    drawRoundedRect(context, 24, 800, 1032, 520, 32);
    context.fill();
    context.restore();

    drawShareCardText(context, card.text, card.reference, true);
  } else {
    // Verse-only card: same frame and gradient, no art panel — the text-only
    // layout from script.js (verse centered in the full card).
    drawShareCardText(context, card.text, card.reference, false);
  }

  return canvas.toDataURL("image/png");
}

// ---------------------------------------------------------------------------
// Deck / interaction
// ---------------------------------------------------------------------------

async function prerenderDeck() {
  const results = await Promise.allSettled(DECK.map((card) => renderCard(card)));
  results.forEach((result, i) => {
    if (result.status === "fulfilled") {
      DECK[i].dataUrl = result.value;
    } else {
      console.warn("Card render failed:", DECK[i].reference, result.reason);
    }
  });

  // Verse-only variants (no image load, so these can't fail like the above).
  const textOnlyResults = await Promise.allSettled(DECK.map((card) => renderCard(card, false)));
  textOnlyResults.forEach((result, i) => {
    if (result.status === "fulfilled") {
      DECK[i].textOnlyDataUrl = result.value;
    }
  });
}

function currentCard() {
  return DECK[deckOrder[deckPosition]];
}

function showCard(card, animate, textOnly = false) {
  const dataUrl = textOnly ? card.textOnlyDataUrl : card.dataUrl;
  if (!dataUrl) return;
  showingTextOnly = textOnly;
  const front = frontIsA ? cardA : cardB;
  const back = frontIsA ? cardB : cardA;

  if (!animate) {
    front.src = dataUrl;
  } else {
    back.src = dataUrl;
    back.classList.add("visible");
    front.classList.remove("visible");
    frontIsA = !frontIsA;
  }
}

function advanceDeck() {
  deckPosition += 1;
  if (deckPosition >= deckOrder.length) {
    // Reshuffle, avoiding an immediate repeat of the card on screen.
    const lastIndex = deckOrder[deckOrder.length - 1];
    do {
      deckOrder = shuffle(DECK.map((_, i) => i));
    } while (deckOrder[0] === lastIndex);
    deckPosition = 0;
  }
}

function press() {
  if (isGenerating) return;
  pressCount += 1;
  advanceDeck();
  const card = currentCard();
  // The free taste is three art cards (boot + two presses). From the third
  // press on, every card arrives verse-only — art now only exists behind
  // generation. The missing picture is what "make it your own" offers.
  const textOnly = pressCount >= CREATE_PROMPT_AFTER_PRESSES || freeArtUsed;
  showCard(card, true, textOnly);
  track("press_me", { reference: card.reference, press_count: pressCount, verse_only: textOnly });

  // Once the free generation is spent, cycling continues verse-only; the
  // pay/registration offer sits on top of the first press and re-offers every
  // third press after a dismissal — same cadence as the create prompt.
  if (freeArtUsed) {
    pressesSinceFreeArt += 1;
    if ((pressesSinceFreeArt - 1) % 3 === 0) {
      paywallModal.hidden = false;
      track("paywall_shown", { after_presses: pressCount });
    }
    return;
  }

  // Prompt shows with the first verse-only card; if dismissed, it re-offers
  // every third press. Returning visitors whose free image is already spent
  // (here or on index.html — same localStorage key, same server counter) get
  // the sign-up offer instead of a free creation they no longer have.
  if (textOnly && (pressCount - CREATE_PROMPT_AFTER_PRESSES) % 3 === 0) {
    if (!isFreeImageAvailable()) {
      if (paywallModal.hidden) {
        paywallModal.hidden = false;
        track("paywall_shown", { after_presses: pressCount });
      }
    } else if (createPrompt.hidden) {
      createPrompt.hidden = false;
      track("create_prompt_shown", { after_presses: pressCount });
    }
  }
  saveSession();
}

function flashLabel(button, label) {
  const original = button.dataset.label || button.textContent;
  button.dataset.label = original;
  button.textContent = label;
  setTimeout(() => {
    button.textContent = original;
  }, 1500);
}

function cardFileName(card) {
  const slug = card.reference
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  return `enlighten-${slug || "scripture"}.png`;
}

function copyVerse() {
  const card = currentCard();
  const payload = `“${card.text}” — ${card.reference} (KJV)`;
  navigator.clipboard.writeText(payload).then(() => flashLabel(copyButton, "Copied"));
  track("card_copied", { reference: card.reference });
}

function saveCard() {
  const card = currentCard();
  const dataUrl = showingTextOnly ? card.textOnlyDataUrl : card.dataUrl;
  if (!dataUrl) return;
  const link = document.createElement("a");
  link.href = dataUrl;
  link.download = cardFileName(card);
  link.click();
  flashLabel(saveButton, "Saved");
  track("share_card_saved", { reference: card.reference });
}

function dataUrlToBlob(dataUrl) {
  const [meta, base64] = dataUrl.split(",");
  const mime = meta.match(/data:(.*?);/)[1];
  const bytes = atob(base64);
  const array = new Uint8Array(bytes.length);
  for (let i = 0; i < bytes.length; i += 1) array[i] = bytes.charCodeAt(i);
  return new Blob([array], { type: mime });
}

async function shareCard() {
  const card = currentCard();
  const payload = `${card.text}\n\n— ${card.reference} (KJV)\nhttps://www.enlighten-me.co`;
  track("share_card_share_started", { reference: card.reference });

  const shareDataUrl = showingTextOnly ? card.textOnlyDataUrl : card.dataUrl;
  if (shareDataUrl && navigator.canShare && navigator.share) {
    const file = new File([dataUrlToBlob(shareDataUrl)], cardFileName(card), { type: "image/png" });
    if (navigator.canShare({ files: [file] })) {
      await navigator.share({ title: "Enlighten-Me", text: payload, files: [file] }).catch(() => {});
      return;
    }
  }
  if (navigator.share) {
    await navigator.share({ text: payload }).catch(() => {});
  } else {
    await navigator.clipboard.writeText(payload);
    flashLabel(shareButton, "Copied");
  }
}

// The real generation call — same request script.js makes, minus the
// subscription branch (this page only serves the free taste; subscribers use
// the main app). The server meters one free image per device id.
async function requestGeneratedArt(card) {
  const response = await fetch(apiUrl("/api/picture"), {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-Enlighten-Product": IMAGE_PRODUCT_ID,
      "X-Enlighten-Device": getDeviceId(),
    },
    body: JSON.stringify({ passage: card.text, reference: card.reference }),
  });

  const payload = await response.json().catch(() => ({}));

  if (response.status === 402) {
    const error = new Error(payload.error || "Your free image has been used.");
    error.code = "free_used";
    throw error;
  }
  if (!response.ok) {
    throw new Error(payload.error || "Image creation failed. Please try again.");
  }

  const src = payload.imageDataUrl || payload.imageUrl;
  if (!src) throw new Error("Image creation finished, but no image came back.");
  return src;
}

async function openCreateModal() {
  if (isGenerating) return;
  const card = currentCard();
  track("create_clicked", { reference: card.reference });
  createPrompt.hidden = true;
  createModal.hidden = false;
  createProgress.hidden = false;
  createDone.hidden = true;
  createError.hidden = true;
  isGenerating = true;

  try {
    const src = await requestGeneratedArt(card);
    card.generatedSrc = src;
    card.dataUrl = await renderCard(card);
    markFreeImageUsed();
    freeArtUsed = true;
    pressesSinceFreeArt = 0;
    track("free_image_generated", { reference: card.reference, tier: "free" });

    // The reveal: the generated card fades in behind the modal, so closing it
    // lands on the finished card. Every press after this hits the paywall.
    showCard(card, true);
    createProgress.hidden = true;
    createDone.hidden = false;
    saveSession();
  } catch (error) {
    createProgress.hidden = true;
    if (error.code === "free_used") {
      // Spent on another page/device-reset — sync local state and offer sign-up.
      markFreeImageUsed();
      createModal.hidden = true;
      paywallModal.hidden = false;
      track("free_image_wall", { reference: card.reference });
    } else {
      createErrorBody.textContent = error.message || "Please try again in a moment.";
      createError.hidden = false;
      track("create_failed", { reference: card.reference });
    }
  } finally {
    isGenerating = false;
  }
}

pressMeButton.addEventListener("click", press);
// Fires on every same-tab departure (settings gear, subscribe handoff, tab
// close) — the belt to the per-mutation braces above.
window.addEventListener("pagehide", saveSession);
copyButton.addEventListener("click", copyVerse);
saveButton.addEventListener("click", saveCard);
shareButton.addEventListener("click", shareCard);
createButton.addEventListener("click", openCreateModal);
dismissPrompt.addEventListener("click", () => {
  createPrompt.hidden = true;
  track("create_prompt_dismissed", {});
});
closeModal.addEventListener("click", () => {
  createModal.hidden = true;
});
createErrorClose.addEventListener("click", () => {
  createModal.hidden = true;
  // The free creation wasn't spent; let them try again from the prompt.
  if (isFreeImageAvailable()) createPrompt.hidden = false;
});
paywallSignup.addEventListener("click", () => {
  track("paywall_signup_clicked", {});
  window.location.href = "/?view=subscribe&return=art-first";
});
paywallClose.addEventListener("click", () => {
  paywallModal.hidden = true;
  track("paywall_dismissed", {});
});
document.getElementById("appStoreLink")?.addEventListener("click", () => {
  track("app_store_clicked", {});
});

document.addEventListener("keydown", (event) => {
  if ((event.code === "Space" || event.code === "Enter") && createModal.hidden && paywallModal.hidden && document.activeElement === document.body) {
    event.preventDefault();
    press();
  }
});

(async () => {
  const restored = restoreSession();
  if (!restored) deckOrder = shuffle(DECK.map((_, i) => i));
  await prerenderDeck();
  showCard(currentCard(), false, restored ? restored.textOnly : false);
  document.body.classList.add("deck-ready");
  track("web_visit", { source: "art-first", restored: Boolean(restored) });
})();
